# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: net/net.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='net/net.proto',
  package='net',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rnet/net.proto\x12\x03net\"\x1b\n\x0bRequestData\x12\x0c\n\x04text\x18\x01 \x01(\t\"\x1c\n\x0cResponseData\x12\x0c\n\x04text\x18\x01 \x01(\t\"%\n\x07SQLTree\x12\x0b\n\x03sql\x18\x01 \x01(\t\x12\r\n\x05sites\x18\x02 \x01(\t\"\x1a\n\tTableData\x12\r\n\x05table\x18\x01 \x01(\t2j\n\nNetService\x12\x32\n\tSimpleFun\x12\x10.net.RequestData\x1a\x11.net.ResponseData\"\x00\x12(\n\x06\x45xcute\x12\x0c.net.SQLTree\x1a\x0e.net.TableData\"\x00\x62\x06proto3'
)




_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='net.RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='net.RequestData.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=22,
  serialized_end=49,
)


_RESPONSEDATA = _descriptor.Descriptor(
  name='ResponseData',
  full_name='net.ResponseData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='net.ResponseData.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=79,
)


_SQLTREE = _descriptor.Descriptor(
  name='SQLTree',
  full_name='net.SQLTree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sql', full_name='net.SQLTree.sql', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sites', full_name='net.SQLTree.sites', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=118,
)


_TABLEDATA = _descriptor.Descriptor(
  name='TableData',
  full_name='net.TableData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='table', full_name='net.TableData.table', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['RequestData'] = _REQUESTDATA
DESCRIPTOR.message_types_by_name['ResponseData'] = _RESPONSEDATA
DESCRIPTOR.message_types_by_name['SQLTree'] = _SQLTREE
DESCRIPTOR.message_types_by_name['TableData'] = _TABLEDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RequestData = _reflection.GeneratedProtocolMessageType('RequestData', (_message.Message,), {
  'DESCRIPTOR' : _REQUESTDATA,
  '__module__' : 'net.net_pb2'
  # @@protoc_insertion_point(class_scope:net.RequestData)
  })
_sym_db.RegisterMessage(RequestData)

ResponseData = _reflection.GeneratedProtocolMessageType('ResponseData', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATA,
  '__module__' : 'net.net_pb2'
  # @@protoc_insertion_point(class_scope:net.ResponseData)
  })
_sym_db.RegisterMessage(ResponseData)

SQLTree = _reflection.GeneratedProtocolMessageType('SQLTree', (_message.Message,), {
  'DESCRIPTOR' : _SQLTREE,
  '__module__' : 'net.net_pb2'
  # @@protoc_insertion_point(class_scope:net.SQLTree)
  })
_sym_db.RegisterMessage(SQLTree)

TableData = _reflection.GeneratedProtocolMessageType('TableData', (_message.Message,), {
  'DESCRIPTOR' : _TABLEDATA,
  '__module__' : 'net.net_pb2'
  # @@protoc_insertion_point(class_scope:net.TableData)
  })
_sym_db.RegisterMessage(TableData)



_NETSERVICE = _descriptor.ServiceDescriptor(
  name='NetService',
  full_name='net.NetService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=254,
  methods=[
  _descriptor.MethodDescriptor(
    name='SimpleFun',
    full_name='net.NetService.SimpleFun',
    index=0,
    containing_service=None,
    input_type=_REQUESTDATA,
    output_type=_RESPONSEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='Excute',
    full_name='net.NetService.Excute',
    index=1,
    containing_service=None,
    input_type=_SQLTREE,
    output_type=_TABLEDATA,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_NETSERVICE)

DESCRIPTOR.services_by_name['NetService'] = _NETSERVICE

# @@protoc_insertion_point(module_scope)
